name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  docker-code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create .env file from example
      run: cp .env.example .env
    - name: Set up Docker Compose
      run: docker compose -f docker-compose.yml up -d --build

    - name: Run ESLint in container
      run: docker compose exec -T app npm run lint

    - name: Run Prettier check in container
      run: docker compose exec -T app npx prettier --check .

    - name: Run tests
      run: docker compose exec -T app npm test